INSERT INTO PRIORIDADE (TIPO) VALUES ('Alta'), ('Normal'), ('Baixa');
INSERT INTO SITUACAO (STATUS) VALUES ('Aberta'),('Expirada'),('Concluida');

INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (1,1,null,'2021-08-26','2021-08-26','Minha tarefa','definição da primeira tarefa para teste no database');
INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (1,2,null,'2019-11-24','2018-08-26','Segunda tarefinha','outra dedicadas ao aprendizado');
INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (2,1,null,'2021-08-26','2021-08-26','Compras','Comprar cebola para o churrasco');
INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (2,1,'2021-08-26','2021-08-26','2021-08-26','Finalizada','Primeira finalizada pro teste');
INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (3,3,'2014-09-05','2014-09-05','2014-09-05','Encher linguiça','apenas um texto no dedo');
INSERT INTO TAREFA (ID_PRIORIDADE,ID_SITUACAO,CONCLUIDA,DEADLINE,INICIO,TITULO,TAREFA) VALUES (1,1,null,'2019-08-26','2019-05-12','Zelda','Jogar Zelda- Majoras mask no emulador, porque sou pobre =)');